name: Download GodotSteam


description: Download and extract the GodotSteam source code for use in compiling


runs:
  using: "composite"

  steps:
    - name: Download and extract GodotSteam
      uses: actions/checkout@v4
      with:
        path: "godotsteam_server"
        ref: "godot3"

    - name: Copy GodotSteam
      shell: bash
      run: |
        cp -r godotsteam_server ./modules/godotsteam_server