on:
  workflow_call:
    inputs:
      godotsteam_server_version:
        required: true
        type: string

    secrets:
      steamworks_sdk_repo:
        required: true

      steamworks_sdk_repo_token:
        required: true


jobs:
  create-bundle:
    runs-on: ubuntu-latest

    name: Create ${{ inputs.platform }} Bundle

    steps:
      - uses: actions/checkout@v4

      # Mac templates
      - name: Download MacOS Server Release Template
        uses: actions/download-artifact@v4
        with:
          name: macos-server-release-template
          path: files

      - name: Download MacOS Server Debug Template
        uses: actions/download-artifact@v4
        with:
          name: macos-server-debug-template
          path: files

      - name: Download MacOS Steam File
        uses: actions/download-artifact@v4
        with:
          name: macos-steam
          path: files

      # Linux 64-bit templates
      - name: Download Linux Server 64-bit Release Template
        uses: actions/download-artifact@v4
        with:
          name: linux64-server-release-template
          path: files

      - name: Download Linux Server 64-bit Debug Template
        uses: actions/download-artifact@v4
        with:
          name: linux64-server-debug-template
          path: files

      - name: Download Linux 64-bit Steam File
        uses: actions/download-artifact@v4
        with:
          name: linux64-steam
          path: files

      # Linux 32-bit templates
      - name: Download Linux Server 32-bit Release Template
        uses: actions/download-artifact@v4
        with:
          name: linux32-server-release-template
          path: files

      - name: Download Linux Server 32-bit Debug Template
        uses: actions/download-artifact@v4
        with:
          name: linux32-server-debug-template
          path: files

      - name: Download Linux 32-bit Steam File
        uses: actions/download-artifact@v4
        with:
          name: linux32-steam
          path: files

      # Windows 64-bit templates
      - name: Download Windows Server 64-bit Release Template
        uses: actions/download-artifact@v4
        with:
          name: windows64-server-release-template
          path: files

      - name: Download Windows Server 64-bit Debug Template
        uses: actions/download-artifact@v4
        with:
          name: windows64-server-debug-template
          path: files

      - name: Download Windows 64-bit Steam File
        uses: actions/download-artifact@v4
        with:
          name: windows64-steam
          path: files

      # Windows 32-bit templates
      - name: Download Windows Server 32-bit Release Template
        uses: actions/download-artifact@v4
        with:
          name: windows32-server-release-template
          path: files

      - name: Download Windows Server 32-bit Debug Template
        uses: actions/download-artifact@v4
        with:
          name: windows32-server-debug-template
          path: files

      - name: Download Windows 32-bit Steam File
        uses: actions/download-artifact@v4
        with:
          name: windows32-steam
          path: files

      - name: Create Template Bundle
        run: |
          zip -j godotsteam_server-gdextension-plugin-${{ inputs.godotsteam_server_version }}.zip files/*
      
      # Zip stuff
      - name: Upload Artifacts Bundle
        uses: ./.github/actions/upload-artifact
        with:
          name: godotsteam_server-gdextension-plugin-${{ inputs.godotsteam_server_version }}.zip
          path: godotsteam_server-gdextension-plugin-${{ inputs.godotsteam_server_version }}.zip